environment          = "dev"
lambda_function_name = "my_lambda_function"
lambda_handler       = "lambda_function.lambda_handler"
lambda_s3_bucket     = "my-aw-sdemo"
lambda_s3_key        = "lambda_function.zip"
terraform_state_file_key = "lambda-module/dev/terraform.tfstate"